include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += FreeRTOS
LOCAL_SRCS      += rtos.c


##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

