include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += ssv_lib.c lib-impl.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

