include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += Source
LOCAL_SRCS	+= rtos_glue.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

