config_setting(
    name = "osx-x86_64",
    values = {"host_cpu": "darwin"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "windows-x86_64",
    values = {"host_cpu": "x64_windows"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "linux-x86_64",
    values = {"host_cpu": "k8"},
    visibility = ["//visibility:public"],
)
