include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += cmd_engine.c soft-main.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

