include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += portable
LOCAL_SRCS      += croutine.c
LOCAL_SRCS      += list.c
LOCAL_SRCS      += queue.c
LOCAL_SRCS      += tasks.c
LOCAL_SRCS      += timers.c


##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

