# Build Configuration for Travis
dist: trusty

language: cpp

env:
  global:
    - CPPFLAGS=""
    - CFLAGS="-Werror --coverage"
    - CXXFLAGS="-Werror -Wno-deprecated-register --coverage" # glib uses register and clang raises a warning
    - LDFLAGS="--coverage"
    - CONFIGURE_OPTS="--with-freetype --with-glib --with-gobject --with-cairo --with-icu --with-graphite2"
    - NOCONFIGURE=1

matrix:
  include:
    - os: linux
      compiler: gcc
      script:
        - ./autogen.sh
        - ./configure $CONFIGURE_OPTS --enable-gtk-doc
        - make
        - make check || (cat */test-suite.log test/*/test-suite.log && false)
      after_success:
        - bash .ci/run-coveralls.sh # for coveralls.io code coverage tracking
        - bash .ci/deploy-docs.sh

    - os: linux
      compiler: clang
      script:
        - ./autogen.sh
        - ./configure $CONFIGURE_OPTS
        - make
        - make check || (cat */test-suite.log test/*/test-suite.log && false)

    - os: osx
      compiler: clang
      install:
          # https://github.com/harfbuzz/harfbuzz/issues/345
        - export CXXFLAGS="$CXXFLAGS -Wno-deprecated-declarations"
        - brew update;
          # Workaround Travis/brew bug
        - brew uninstall libtool && brew install libtool
        - brew install ragel freetype glib gobject-introspection cairo icu4c graphite2
        - brew link --force icu4c # icu4c is keg-only
      script:
        - ./autogen.sh
        - ./configure $CONFIGURE_OPTS --with-coretext
        - make
        - make check || (cat */test-suite.log test/*/test-suite.log && false)

notifications:
  irc: "irc.freenode.org#harfbuzz"
  email: harfbuzz@lists.freedesktop.org

addons:
  apt:
    packages:
      - pkg-config # for autogen.sh
      - ragel
      - gtk-doc-tools
      - libfreetype6-dev # for font function
      - libglib2.0-dev # for font functions / tests / utils
      - libcairo2-dev # for utils
      - libicu-dev # for extra unicode functions
      - libgraphite2-dev # for extra shapers
      - # libgirepository1.0-dev # for gobject-introspection
