/*
 * Copyright (c) 2015 iComm-semi Ltd.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef CABRIO_H
#define CABRIO_H

#define SSV_VENDOR_ID		0x3030
#define SSV_CABRIO_DEVID	0x3030

#define	SSV_SUBVENDOR_ID_NOG	0x0e11
#define SSV_SUBVENDOR_ID_NEW_A	0x7065
#define SSV_CABRIO_MAGIC	0x19641014


#define SSV_AMPDU_LIMIT_MAX	(64 * 1024 - 1)

#define	SSV_DEFAULT_NOISE_FLOOR -95

#define SSVCABRIO_RSSI_BAD	-128

#define SSVCABRIO_NUM_CHANNELS	38


#endif // CABRIO_H
