include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += SSV6200
LOCAL_SRCS	+= 


##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

