include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        += GCC MemMang
LOCAL_SRCS      += 


##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

