# This file was auto-generated by test/vts-testcase/fuzz/script/update_makefiles.py.
# Do not edit manually.

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := VtsHalGraphicsComposerV2_1IfaceFuzzer
include test/vts/tools/build/Android.host_config.mk
