java_import(
    name = "google-api-java-client-min-repackaged-1.23.0",
    jars = ["google-api-java-client-min-repackaged-1.23.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
