include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += drv_phy.c

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

