include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS	+= heap_3.c


##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

