include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += bsp.c
LOCAL_SRCS      += cpu.c
LOCAL_SRCS      += irq.c
LOCAL_SRCS      += serial.c
LOCAL_ASMS	+= boot.S

##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

