my_robolectric_runtime_deps := \
    lib/accessibility-test-framework-2.1.jar \
    lib/annotations-3.6.1.jar \
    lib/asm-6.0.jar \
    lib/asm-commons-6.0.jar \
    lib/asm-tree-6.0.jar \
    lib/bcprov-jdk15on-1.52.jar \
    lib/commons-codec-1.3.jar \
    lib/commons-logging-1.1.1.jar \
    lib/guava-20.0.jar \
    lib/hamcrest-core-1.3.jar \
    lib/hamcrest-library-1.3.jar \
    lib/httpclient-4.0.3.jar \
    lib/httpcore-4.0.1.jar \
    lib/icu4j-53.1.jar \
    lib/junit-3.6.1.jar \
    lib/protobuf-java-2.6.1.jar \
    lib/resources-3.6.1.jar \
    lib/robolectric-3.6.1.jar \
    lib/sandbox-3.6.1.jar \
    lib/shadowapi-3.6.1.jar \
    lib/shadows-framework-3.6.1.jar \
    lib/shadows-httpclient-3.6.1.jar \
    lib/shadows-multidex-3.6.1.jar \
    lib/shadows-playservices-3.6.1.jar \
    lib/shadows-supportv4-3.6.1.jar \
    lib/sqlite4java-0.282.jar \
    lib/utils-3.6.1.jar \
    lib/vtd-xml-2.11.jar \
    lib/xmlpull-1.1.3.1.jar \
    lib/xpp3_min-1.1.4c.jar \
    lib/xstream-1.4.8.jar 
