all:
	$(MAKE) -f Makefile.lib
	$(MAKE) -f Makefile.airkiss
	$(MAKE) -f Makefile.qqlink
	$(MAKE) -f Makefile.smarticomm

clean:
	$(MAKE) -f Makefile.lib     clean
	$(MAKE) -f Makefile.airkiss clean
	$(MAKE) -f Makefile.qqlink  clean
	$(MAKE) -f Makefile.smarticomm clean
	
