include $(TOPDIR)/config.mk

INCLUDE         +=
SRC_DIRS        +=
LOCAL_SRCS      += port.c
LOCAL_SRCS      += portISR.c


##############################################################
# make rules
##############################################################
include $(TOPDIR)/rules.mk

