# Part of the standalone-jps-builder artifact from IDEA
java_import(
    name = "formc-deps",
    jars = [
        "asm-all.jar",
        "jdom.jar",
        "jgoodies-forms.jar",
        "jps-builders.jar",
    ],
    visibility = ["//tools/base/bazel:__pkg__"],
)
