application: chromeoswideprofiling
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /
  script: server.py
- url: /upload
  script: server.py
- url: /serve
  script: server.py
- url: /serve/.*
  script: server.py
- url: /del/.*
  script: server.py
